[build]
  # Build command for the project
  command = "cd packages/shared && bun run build && cd ../../apps/frontend && bun install && bun run build"
  
  # Build directory (where static files are located)
  publish = "apps/frontend/dist"
  
  # Base directory of the project
  base = "."
  
  # Deploy only when frontend or shared files change
  ignore = "bash scripts/ignore-netlify-build.sh"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Install Bun
  BUN_VERSION = "1.2.4"

# Redirects for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
