[build]
  # Comando para buildar o projeto
  command = "cd packages/shared && bun run build && cd ../../apps/frontend && bun install && bun run build"
  
  # Diretório de build (onde estão os arquivos estáticos)
  publish = "apps/frontend/dist"
  
  # Diretório base do projeto
  base = "."
  
  # Deploy apenas quando frontend ou shared mudarem
  ignore = "bash scripts/ignore-netlify-build.sh"

[build.environment]
  # Versão do Node.js
  NODE_VERSION = "18"
  
  # Instalar Bun
  BUN_VERSION = "1.2.4"

# Redirects para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
