[build]
command = "cd packages/shared && bun install && bun run build && cd ../../apps/backend && bun install"

[deploy]
startCommand = "cd apps/backend && bun run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
